# Generated by Django 4.2.8 on 2025-12-11 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EyeTrackingTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_date", models.DateTimeField(auto_now_add=True)),
                ("duration", models.FloatField(help_text="Durée totale en secondes")),
                (
                    "gaze_time",
                    models.FloatField(help_text="Temps de fixation en secondes"),
                ),
                (
                    "tracking_percentage",
                    models.FloatField(help_text="Pourcentage de suivi"),
                ),
                ("fixation_count", models.IntegerField()),
                (
                    "avg_fixation_duration",
                    models.FloatField(help_text="Durée moyenne des fixations en ms"),
                ),
                (
                    "max_fixation_duration",
                    models.FloatField(help_text="Durée max des fixations en ms"),
                ),
                (
                    "min_fixation_duration",
                    models.FloatField(help_text="Durée min des fixations en ms"),
                ),
                (
                    "avg_eye_screen_distance",
                    models.FloatField(
                        blank=True, help_text="Distance moyenne en cm", null=True
                    ),
                ),
                (
                    "gaze_stability",
                    models.FloatField(help_text="Score de stabilité (0-1)"),
                ),
                (
                    "gaze_consistency",
                    models.FloatField(help_text="Score de cohérence (0-1)"),
                ),
                ("left_eye_open", models.BooleanField()),
                ("right_eye_open", models.BooleanField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Bon"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Faible"),
                        ],
                        max_length=20,
                    ),
                ),
                ("clinical_evaluation", models.TextField()),
                ("recommended_follow_up", models.BooleanField(default=False)),
                ("raw_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Test de suivi oculaire",
                "verbose_name_plural": "Tests de suivi oculaire",
                "ordering": ["-test_date"],
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Patient",
                "verbose_name_plural": "Patients",
            },
        ),
        migrations.CreateModel(
            name="MLPrediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "predicted_result",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent"),
                            ("good", "Bon"),
                            ("acceptable", "Acceptable"),
                            ("poor", "Faible"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(help_text="Confiance de la prédiction (0-1)"),
                ),
                ("features", models.JSONField()),
                ("anomaly_detected", models.BooleanField(default=False)),
                ("anomaly_score", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ml_prediction",
                        to="api.eyetrackingtest",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédiction ML",
                "verbose_name_plural": "Prédictions ML",
            },
        ),
        migrations.AddField(
            model_name="eyetrackingtest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tests",
                to="api.patient",
            ),
        ),
    ]
